// changePassword, bulkUpdate needs to be changed
const iconsMapping = {
  add: 'add',
  update: 'icomoon-edit-empty',
  delete: 'icomoon-delete-empty',
  approve: 'icomoon-tick-circled',
  reject: 'cross-circled',
  save: 'icomoon-save',
  cancel: 'icomoon-close',
  notify: 'sms',
  notifyCustomer: 'sms',
  more: 'filter-funnel',
  assignNow: 'filter-funnel',
  bulkUpdate: 'bulk-update',
  changePwd: 'unlock',
  mapview: 'map-view',
  listview: 'list-view',
  timelineview: 'latesr-activity',
  preview: 'icon icon-edit',
  printManifest: 'print',
  markAsHandover: 'markAsHandover',
  overrideStatus: 'icomoon-refresh',
  cloneOrder: 'copy-empty',
  cloneRole: 'copy-empty',
  cloneAccessProfile:'copy-empty',
  calendar:'calendar',
  optimizePacking: 'optimize-packing',
  manualAssign: 'icomoon-puzzle',
  printAwb: 'print',
  printMultiDrs: 'print',
  showdrs: 'showdrs',
  startTrip: 'starttrip',
  stopTrip: 'stoptrip',
  'Mark as Favourite': 'star-filled',
  'printManifestLabel': 'print',
  reviseETA: 'clock-history-outline'
}

export default iconsMapping