/** Declaration file generated by dts-gen */

export function geocodeByAddress(address: any): any;

export function geocodeByPlaceId(placeId: any): any;

export function getLatLng(result: any): any;

