export const pageValueFromKey = {
  SUBSCRIPTION: "subscriptionPage",
  CLIENT: "clientPage",
};

export const paramsFromSubscriptionName = {
  RESOURCEBASED: "RESOURCELIMIT,TOTALEMAILLIMIT,TOTALSMSLIMIT,TOTALIVRLIMIT",
  TRANSACTIONBASED: "ORDERLIMIT,TOTALEMAILLIMIT,TOTALSMSLIMIT,TOTALIVRLIMIT",
};
