export const inviteUserStructure = {
  User1: {
    label: "User 1",
    fieldName: "User",
    fieldType: "text",
    permission: true,
    id: "user1",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    labelKey: "User Name",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    error: true,
    errorMessage: 'Invalid Email',
    validation: {
      required: {
        message: "User 1 Name is mandatory.",
      },
    },
  },
  Email1: {
    label: "Email ID 1",
    fieldName: "Email",
    fieldType: "email",
    permission: true,
    id: "email1",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    labelKey: "Email ID",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    isError: false,
    errorType: "required",
    nonDuplicateError: false,
    duplicateError: false,
    validation: {
      required: {
        message: "This email is not allowed",
      },
    },
  },
  User2: {
    label: "User 2",
    fieldName: "User",
    fieldType: "text",
    permission: true,
    id: "user2",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {
      required: {
        message: "User 2 is mandatory.",
      },
    },
    labelKey: "User Name",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
  },
  Email2: {
    label: "Email ID 2",
    fieldName: "Email",
    fieldType: "email",
    permission: true,
    id: "email2",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {
      required: {
        message: "This email is not allowed.",
      },
    },
    labelKey: "Email ID",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    isError: false,
    errorType: "required",
    nonDuplicateError: false,
    duplicateError: false,
  },
  User3: {
    label: "User 3",
    fieldName: "User",
    fieldType: "text",
    permission: true,
    id: "user3",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {},
    labelKey: "User Name",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
  },
  Email3: {
    label: "Email ID 3",
    fieldName: "Email",
    fieldType: "email",
    permission: true,
    id: "email3",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {
      required: {
        message: "This email is not allowed.",
      },
    },
    labelKey: "Email ID",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    isError: false,
    errorType: "required",
    nonDuplicateError: false,
    duplicateError: false,
  },
  User4: {
    label: "User 4",
    fieldName: "User",
    fieldType: "text",
    permission: true,
    id: "user4",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {},
    labelKey: "User Name",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
  },
  Email4: {
    label: "Email ID 4",
    fieldName: "Email",
    fieldType: "email",
    permission: true,
    id: "email4",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    labelKey: "Email ID",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    isError: false,
    errorType: "required",
    nonDuplicateError: false,
    duplicateError: false,
    validation: {
      required: {
        message: "This email is not allowed.",
      },
    },
  },
  User5: {
    label: "User 5",
    fieldName: "User",
    fieldType: "text",
    permission: true,
    id: "user5",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {},
    labelKey: "User Name",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
  },
  Email5: {
    label: "Email ID 5",
    fieldName: "Email",
    fieldType: "email",
    permission: true,
    id: "email5",
    required: false,
    childLength: 0,
    rowSpan: 0,
    colSpan: 0,
    validation: {
      required: {
        message: "This email is not allowed.",
      },
    },
    labelKey: "Email ID",
    isLocked: true,
    excelDropDownHidden: false,
    editable: true,
    searchable: false,
    sortable: false,
    customField: false,
    allowed: false,
    infoFlag: false,
    isError: false,
    errorType: "required",
    nonDuplicateError: false,
    duplicateError: false,
  },
};